### ISSUE TITLE
 complex noise

### ISSUE THREAD

**Issue by YuefeiZ** [Zeqiang-Lai/DPHSIR#2]
您好，在代码里没有看到处理complex noise的代码。请问在处理complex noise时，denoiser(tmp, sigma)中的sigma是怎么给出的？

**Comment by Zeqiang-Lai** [comment]
我们使用没有noise level map的网络处理complex noise。

https://github.com/Zeqiang-Lai/DPHSIR/blob/0bcf0d0933091ea65acd23f31150c01d775f846f/dphsir/denoisers/models/qrnn/__init__.py#L40

**Comment by YuefeiZ** [comment]
感谢您的回答。请问您，在处理complex noise时，有用到迭代求解吗？即solver = ADMMSolver(init,** prox, denoise).to(device)。还是像在处理高斯时一样，直接求解的，没用进行迭代？

**Comment by Zeqiang-Lai** [comment]
是的，没有用到迭代求解。

**Comment by YuefeiZ** [comment]
感谢您的回答。还有一点我不是很明白，您在文章中写道，在训练complex noise时，采用的是训练高斯噪声的训练策略训练了50轮。而您在训练高斯噪声时，写的是 further finetune,也就是说，在训练高斯噪声时，首先对噪声层级为50的高斯噪声训练了30轮，然后再对随机的四个固定噪声层级训练了20轮？是这样吗？

**Comment by Zeqiang-Lai** [comment]
是的，我们follow了[QRNN3D](https://github.com/Vandermode/QRNN3D)的训练策略，先在30强度的高斯噪声上训30epoch，然后在随机的四个固定噪声层级训练20epoch，作为高斯去噪的模型。complex是在高斯去噪50epoch的基础上在complex noise 继续训50epoch，具体训练的策略和代码可以参考QRNN3D。

**Comment by YuefeiZ** [comment]
好的，感谢您的解答，谢谢！

**Comment by Zeqiang-Lai** [comment]
不客气
